### ISSUE TITLE
cache-require-paths is redundant

### ISSUE THREAD

**Issue by maxlk** [lookfirst/gulp-helpers#17]
**cache-require-paths** is redundant in **gulp-helpers** by the following reasons:
- it doesn't relate to **gulp** in any way;
- it doesn't add any functionality (it improves performance in some specific cases, but not everyone needs it);
- it alternates behavior of node's `require()` and consumer of **gulp-helpers** is not aware of it;
- it leads to not obvious errors when dependencies are added/removed to consuming project.

The decision to use or not to use it should be done by actual project and should not be imposed by utility like **gulp-helpers**. 
For example: I'm working on immature project and we are experimenting a lot with different 3rd parties and we remove/add new dependencies in a daily manner, so it only interferes us. It even blocked us when we faced _"cannot find module"_ error first time, **nodejs** module-loading worked against documented behavior and there was no any indication that something overrode it.

**Comment by lookfirst** [comment]
Submit a PR to remove and I'm fine with that. It was an experiment and I agree that it has only caused more pain than benefit. =)

**Comment by lookfirst** [comment]
I'm going to close this in favor of a PR.
