### ISSUE TITLE
browserSync task fails with `Promise is not defined`

### ISSUE THREAD

**Issue by barneycarroll** [lookfirst/gulp-helpers#3]
…because Babel polyfills haven't been imported?

> ReferenceError: Promise is not defined
>  at Gulp.<anonymous> (./node_modules/gulp-helpers/dist/tasks/browserSync.js:42:10)

ie https://github.com/lookfirst/gulp-helpers/blob/master/src/tasks/browserSync.js#L25

**Comment by barneycarroll** [comment]
Babel depends upon some native polyfills, but [don't recommend using this in a library](http://babeljs.io/docs/usage/require/) (presumably to avoid screwing around with the entire environment). So for the time being I'm marking this as an unregistered dependency of running gulp-helpers and chucking in `require( 'babel/register' )` before requiring `gulp-helpers`, at which point everything plays nice.

Might be worth forking an ES5 version?

**Comment by lookfirst** [comment]
I just don't get how this is working fine on Travis all the way back to node 0.10. =(

https://travis-ci.org/lookfirst/systemjs-seed/jobs/56666400

Which version of node are you using?

**Comment by lookfirst** [comment]
Ok, this should be fixed with the `optional: runtime` setting in babel, which causes corejs to be used...

**Comment by barneycarroll** [comment]
Cool. Came running back to this after my attempt at a modest JSPM transpilation workflow ended up far more involved than I would have hoped (remember makefiles? Those were the days…). However I couldn't get the demo to work. Will try again this evening.

**Comment by lookfirst** [comment]
Oh, I do. I used to port software to A/UX. http://markmail.org/message/f4q7w6266bbjctvx (search for Jon Stevens)   circa 1996
