### ISSUE TITLE
PhantomJS dependency

### ISSUE THREAD

**Issue by lawrencejones** [lookfirst/gulp-helpers#32]
Hey,

I really like this idea of this library and how it cleans up your average gulpfile. Unfortunately I'm finding the cost of all the dependencies to be quite significant when running CI builds etc.

One particularly annoying dependency is the `karma-phantomjs-launcher` dependency. This forces a download of the phantom binary on every `npm install` which is really costly when you don't make use of this package- in fact, removing this dependency halves `npm install` time on my machine.

Is there any way I could persuade you to drop this from your `package.json`?

Thanks!

**Comment by lookfirst** [comment]
Definitely. I'll take a look into that today. =)

**Comment by lookfirst** [comment]
Removed. v5.0.0

**Comment by lawrencejones** [comment]
This response was awesome, thank you for being so available and so fast!

**Comment by lookfirst** [comment]
:+1:
