### ISSUE TITLE
Breaking change to connect-history-api-fallback causes issues.

### ISSUE THREAD

**Issue by kkruit** [lookfirst/gulp-helpers#4]
[connect-history-api-fallback v1.0.0](https://github.com/bripkens/connect-history-api-fallback/blob/master/CHANGELOG.md#v100) added configurations. This basically changes the plugin to be a factory instead of an object. 

The effect is that when you include this module in the browserSync task all requests to the local server hang and get no response.

I'm working on a PR for this issue now.

**Comment by lookfirst** [comment]
Merged.
