### ISSUE TITLE
Fails to install on windows

### ISSUE THREAD

**Issue by Hypercubed** [lookfirst/gulp-helpers#6]
It may be only my machine but I cannot install this module (or modules that depend on it) because of this line in the package file:

`"gulp-ng-html2js": "lookfirst/gulp-ng-html2js#export2"`

Works if I change to:

`"gulp-ng-html2js": "*"`

**Comment by osdevisnot** [comment]
Same Issue Here, There is no export2 branch or tag on gulp-ng-html2js. Valid install targets : ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.6","0.1.7","0.1.8","0.2.0"]

**Comment by lookfirst** [comment]
What version of npm are you using?

This is the branch/project... https://github.com/lookfirst/gulp-ng-html2js/tree/export2

I've made some changes to the parent ng-html2js project to better support exporting the modules. Sadly, the parent project refuses to accept these changes as a PR. =(

**Comment by osdevisnot** [comment]
node -v v0.10.28
npm -v 1.4.9

**Comment by lookfirst** [comment]
I'm guessing you are going to have to upgrade in order to support branches as versions in package.json files.

**Comment by osdevisnot** [comment]
I did not pay attention to what version NPM started supporting branch installs, this works after upgrade.

**Comment by Hypercubed** [comment]
My version:

node -v v0.12.0
npm -v 2.5.1
git version 2.1.4

But I am running Cygwin on Windows which has issues on occasion.

**Comment by lookfirst** [comment]
What's the error you're getting? I don't know what version npm was fixed in, but running latest npm might help.

**Comment by Hypercubed** [comment]
I'm convinced that this is a cygwin issue.  I can install under windows command line.  I think branch installs are not working on cygwin, which is not officially supported by npm anyway.

Closing.

**Comment by lookfirst** [comment]
I would make absolutely sure that cygwin is using the latest version of npm.

**Comment by Hypercubed** [comment]
It is using a new enough version (2.5.1).  It works fine on the windows command shell.  For some reason when I try Cygwin the paths get mangled.  That's unfortunately not uncommon when using Cygwin.

**Comment by lookfirst** [comment]
Right... my point is that the path mangling might be fixed in a newer version of npm. 2.8.3 is latest.
